### PR TITLE
rustup

### PR DESCRIPTION
**Pull request by globin**

### CODE REVIEW

**Comment by maxsnew** [comment]
I'm getting the same error on my local machine as on Travis:
```
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
note: write `[..]` instead
/home/max/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/graph.rs:4:49: 4:55 error: unresolved import `std::collections::hash_map::Hasher`. There is no `Hasher` in `std::collections::hash_map`
/home/max/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/graph.rs:4 use std::collections::hash_map::{HashMap, Keys, Hasher};
                                                                                                                                       ^~~~~~
/home/max/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/dependency_queue.rs:8:43: 8:49 error: unresolved import `std::collections::hash_map::Hasher`. There is no `Hasher` in `std::collections::hash_map`
/home/max/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/dependency_queue.rs:8 use std::collections::hash_map::{HashMap, Hasher};
                                                                                                                                            ^~~~~~
error: aborting due to 2 previous errors
Could not compile `cargo`.

To learn more, run the command again with --verbose.
```
with
```
rustc 1.0.0-nightly (2b01a37ec 2015-02-21) (built 2015-02-22)
```
which I got from a fresh rustup.

Is it compiling for you? If so, what version of rustc are you using?

**Comment by globin** [comment]
Yeah I have an updated version of cargo fixed for rust master (rust-lang/cargo#1336)

**Comment by maxsnew** [comment]
I made the `Cargo.toml` point at the branch with your patched cargo on it. I'd appreciate it if you sent a pr here before you delete that branch.

**Comment by maxsnew** [comment]
Nvm I saw that it was merged. I've gone back to cargo `HEAD`. Thanks for the help!

**Pull request merged**
